Add first test to check if set up correctly

diff --git a/bin/fastcheck b/bin/fastcheck
--- a/bin/fastcheck
+++ b/bin/fastcheck
@@ -15,6 +15,7 @@ then
   echo 'SCSS-Lint has detected some issues, commit aborted.'
   exit 1
 fi
+echo 'SCSS-Lint has not found any errors'
 
 echo "\n=== Slim Linting ==="
 if ! bundle exec slim-lint app/views/
@@ -22,15 +23,16 @@ then
   echo 'Slim-Lint has detected some issues, commit aborted.'
   exit 1
 fi
+echo 'Slim-Lint has not found any errors'
 
 echo "\n=== Brakeman Check ==="
-if ! bundle exec brakeman -z --summary -q
+if ! bundle exec brakeman -q -z --no-summary
 then
   echo 'Brakeman has detected some issues, commit aborted.'
   exit 1
 fi
 
-echo "\n=== Reek Check ==="
+echo "=== Reek Check ==="
 if ! bundle exec reek
 then
   echo 'Reek has detected some issues, commit aborted.'
